'use client'

// components/report-sections/peec-ai/sentiment-insights.tsx
// FB-065: Sentiment Insights card, sourced from Profound's API (was an in-house
// Glean call that guessed tone from headlines). Renders exactly Tina's ask:
// a sentiment KPI pill, Positive/Negative themes side by side, and click a
// theme to expand the sources cited. All values are Profound's own data,
// reactive to the date range and model picker; nothing is AI-generated here.

import { useState } from 'react'
import { Sparkles, ChevronRight } from 'lucide-react'
import { InfoTooltip } from '@/components/ui/info-tooltip'
import type { ProfoundSentiment, ProfoundSentimentTheme } from '@/lib/profound/sentiment'

const HEADLINE_TOOLTIP =
  'Share of classified brand mentions that are positive, from Profound. Themes and their cited sources are Profound’s own tagging of the AI answers in the selected period and model. Not AI-generated by this dashboard.'

function hostOf(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, '')
  } catch {
    return url
  }
}

// Pill label/tint. "Negative" requires actual negative themes so the headline
// never contradicts the body (e.g. a low positive share driven by neutral
// mentions with zero negative themes reads "Mixed", not "Negative").
//   >= 75% positive                        -> Positive (green)
//   < 45% positive AND negative themes > 0 -> Negative (red)
//   otherwise                              -> Mixed (yellow)
function pctLabel(p: number, negativeThemeCount: number): string {
  if (p >= 75) return 'Positive'
  if (p < 45 && negativeThemeCount > 0) return 'Negative'
  return 'Mixed'
}

function pctTint(p: number, negativeThemeCount: number): { ring: string; bg: string; text: string } {
  if (p >= 75) return { ring: 'border-[#60FF80]/30', bg: 'bg-[#60FF80]/10', text: 'text-[#60FF80]' }
  if (p < 45 && negativeThemeCount > 0) return { ring: 'border-[#FF4444]/30', bg: 'bg-[#FF4444]/10', text: 'text-[#FF4444]' }
  return { ring: 'border-[#FFD700]/30', bg: 'bg-[#FFD700]/10', text: 'text-[#FFD700]' }
}

function ThemeAccordion({
  title,
  count,
  expanded,
  onToggle,
  children,
}: {
  title: string
  count: number
  expanded: boolean
  onToggle: () => void
  children: React.ReactNode
}) {
  return (
    <div className="rounded-md border border-white/[0.06] bg-white/[0.02]">
      <button
        type="button"
        onClick={onToggle}
        aria-expanded={expanded}
        className="flex w-full items-center gap-2 px-3 py-2.5 text-left transition-colors hover:bg-white/[0.03]"
      >
        <ChevronRight
          className={`h-3.5 w-3.5 shrink-0 text-text-muted transition-transform ${expanded ? 'rotate-90' : ''}`}
        />
        <span className="flex-1 text-sm font-semibold text-white">{title}</span>
        <span className="shrink-0 rounded-full bg-white/[0.06] px-2 py-0.5 text-[10px] font-bold text-text-muted">
          <span className="tabular-nums">{count}</span> mentions
        </span>
      </button>
      {expanded && <div className="border-t border-white/[0.06] px-3 py-3">{children}</div>}
    </div>
  )
}

function SourceList({ urls, accent }: { urls: string[]; accent: string }) {
  if (urls.length === 0) {
    // Profound tagged the theme on real AI answers, but those specific answers
    // did not include citation URLs (some models, e.g. Perplexity, sometimes
    // return uncited answers). We surface this honestly rather than hiding the
    // theme or inventing sources.
    return (
      <p className="text-xs text-text-muted">
        Profound tagged this theme in AI answers that did not include citation URLs.
      </p>
    )
  }
  return (
    <ul className="space-y-1.5">
      {urls.map((url) => (
        <li key={url} className="flex gap-2 text-xs leading-relaxed">
          <span style={{ color: accent }}>&rsaquo;</span>
          <a
            href={url}
            target="_blank"
            rel="noopener noreferrer"
            className="break-all text-white/80 underline-offset-2 hover:text-white hover:underline"
            title={url}
          >
            {hostOf(url)}
            <span className="text-text-muted"> {url.replace(/^https?:\/\/[^/]+/, '') || '/'}</span>
          </a>
        </li>
      ))}
    </ul>
  )
}

function ThemeColumn({
  heading,
  blurb,
  themes,
  accent,
}: {
  heading: string
  blurb: React.ReactNode
  themes: ProfoundSentimentTheme[]
  accent: string
}) {
  const [open, setOpen] = useState<Set<string>>(new Set())
  const toggle = (title: string) => {
    const next = new Set(open)
    if (next.has(title)) next.delete(title)
    else next.add(title)
    setOpen(next)
  }
  return (
    <div className="flex flex-col rounded-lg border border-white/[0.06] bg-bg-surface p-4">
      <h4 className="mb-1 text-base font-bold text-white">{heading}</h4>
      <p className="mb-3 text-xs text-text-muted">{blurb}</p>
      <div className="flex-1 space-y-2 overflow-y-auto pr-1 max-h-[400px]">
        {themes.length === 0 ? (
          <p className="text-xs text-text-muted">No themes detected in this period.</p>
        ) : (
          themes.map((theme, i) => (
            <ThemeAccordion
              key={`${theme.title}-${i}`}
              title={theme.title}
              count={theme.count}
              expanded={open.has(theme.title)}
              onToggle={() => toggle(theme.title)}
            >
              <SourceList urls={theme.urls} accent={accent} />
            </ThemeAccordion>
          ))
        )}
      </div>
    </div>
  )
}

export function SentimentInsights({ data }: { data: ProfoundSentiment | null }) {
  const noData = !data || data.occurrences === 0 || data.positivePct === null

  return (
    <section className="rounded-xl border border-white/[0.08] bg-bg-surface p-6">
      <header className="mb-4 flex flex-wrap items-center gap-3">
        <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#60FF80]/10">
          <Sparkles className="h-4 w-4 text-[#60FF80]" />
        </span>
        <h3 className="text-sm font-bold uppercase tracking-widest text-text-muted">Sentiment Insights</h3>
        <InfoTooltip text={HEADLINE_TOOLTIP} />
        {!noData && (() => {
          const pct = data!.positivePct as number
          const negativeCount = data!.negativeThemes.length
          const tint = pctTint(pct, negativeCount)
          return (
            <span
              className={`ml-auto inline-flex items-center gap-2 rounded-full border ${tint.ring} ${tint.bg} px-3 py-1 text-xs font-bold uppercase tracking-widest ${tint.text}`}
              title="Sentiment headline for the selected date range and model"
            >
              {pctLabel(pct, negativeCount)}
              <span className="tabular-nums">{pct.toFixed(1)}%</span>
            </span>
          )
        })()}
      </header>

      {noData && (
        <p className="text-sm text-text-muted">
          No classified sentiment from Profound for this date range or model selection. Try a wider date range or the all-models view.
        </p>
      )}

      {!noData && (
        <div className="grid gap-5 lg:grid-cols-2 items-stretch">
          <ThemeColumn
            heading="Positive Themes"
            blurb={<>What AI-cited sources say <span className="font-bold text-white">positively</span> about the brand. Click a theme to see the citing sources.</>}
            themes={data!.positiveThemes}
            accent="#60FF80"
          />
          <ThemeColumn
            heading="Negative Themes"
            blurb={<>What AI-cited sources flag as <span className="font-bold text-white">gaps</span>. Click a theme to see the citing sources.</>}
            themes={data!.negativeThemes}
            accent="#FF4444"
          />
        </div>
      )}

      {!noData && (
        <p className="mt-5 border-t border-white/[0.08] pt-4 text-xs leading-relaxed text-text-muted">
          <span className="font-semibold text-white/80">Mentions</span> is how many AI answers brought up a
          theme for the dates and models you&rsquo;ve selected. Open a theme to see the web pages those answers
          linked to most often (top 12). A single answer can link to many pages, so a theme&rsquo;s mention count
          is usually higher than the number of links shown. Everything here comes straight from Profound.
        </p>
      )}
    </section>
  )
}
